### ISSUE TITLE
Umlaute in der json müssen entfernt werden

### ISSUE THREAD

**Issue by flomein** [FlorianMein/LF6ChatBot#4]
In der json Datei sind diverse Umlaute (ä,ö,ü) enthalten. Diese können über die Kommandozeile nicht vernünftig dargestellt werden. Einmal bitte alle Umlaute in der json durch die jeweilige Ersatzschreibweise ersetzen, damit ein vernünftiger Output des Bots entsteht.

**Comment by BT1507** [comment]
shaue ich mir nachher an

**Comment by flomein** [comment]
Sieht gut aus
